### ISSUE TITLE
[RFE]  Enhance "manage.down removekeys=True"

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt-enhancement-proposals#5]
Current removekeys logic is very basic.  It will remove minion in maintenance mode(off the network connection) , they could be down for many days.

Is it possible to add "manage.down_noDNS", ie if minion hostname got removed from DNS server ?

**Comment by gtmanfred** [comment]
you could write a state for this, and run it in an orchestration state.

use jinja to look up minions, and then check their dns hostname with the dns module, and if nothing is returned make a salt.wheel state to remove the key.

**Comment by gtmanfred** [comment]
also this is not what this repository is for, this should be a feature request on the salt repository.

**Comment by Ch3LL** [comment]
this was my fault, apologies. I was mistaken with the difference between feature requests and when one would use this repo so i asked @tjyang to create a enhancement proposal here  Apologies @tjyang 

I went ahead and re-opened the issue here: https://github.com/saltstack/salt/issues/52135
